name: Unit Test

on: push

jobs:
  unit-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
     - uses: actions/checkout@v3
     - uses: actions/setup-node@v3
       with:
          node-version: 18.x
     - uses: ./.github/actions/npm-install
     - name: Unit Test
       run: npm run test

